config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments

    resources :links
    root to: "links#index"

  end
  get 'about', to: 'pages#about'
  resources :contacts
  get 'contact-us', to: 'contacts#new'
  get 'devmatch', to: 'pages#devmatch'
  get 'javascript', to: 'pages#javascript'
  get 'video', to: 'pages#video'
  get 'site', to: 'pages#site'
  get 'java', to: 'pages#java'
  get 'javapage2', to: 'pages#javapage2'
  get 'PacmanGame', to: 'pages#PacmanGame'
  get 'Tetris', to: 'pages#Tetris'
  get 'Loaders', to: 'pages#Loaders'
  get 'SuperMario', to: 'pages#SuperMario'
  get 'Pong', to: 'pages#Pong'
  get 'Reddit', to: 'pages#Reddit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         extend Devise::Models

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comments = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
  @post =Post.find(params[:post_id])
  @comment = @post.comments.find(params[:id])
  @comment.destroy

  redirect_to post_path(@post)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:body]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = "Message Sent!"
      redirect_to new_contact_path
    else
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :comments)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def devmatch
  end

  def javascript
  end

  def video
  end

  def site
  end

  def java
  end

  def javapage2
  end

  def PacmanGame
  end

  def Tetris
  end

  def Loaders
  end

  def SuperMario
  end

  def Pong
  end

  def Reddit
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment-time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <p><%= link_to 'delete', [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?'} %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/contacts/new.html.erb
<div class = "container">
  <div class= 'row'>
    <h3 class = "text-center">Contact Aaron</h3>

    <div class = "col-md-4 col-md-offset-4">
      <div class = 'well'>
        <%= form_for @contact do |f| %>
            <div class = "form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class = "form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class = "form-group">
              <%= f.label :comments %>
              <%= f.text_area :comments, class: 'form-control' %>
            </div>
          <%= f.submit 'Submit', class: 'btn btn-default'%>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
      <title>app</title>
      <%= csrf_meta_tags %>
      <link href="//fonts.googleapis.com/css?family=Eagle+Lake|Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>



    <nav class ="navbar navbar-default navbar-static-top" role="navigation">
        <div class= "container">
      <div class ="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle= "collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class ="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--Hamburger Menu -->
        <div id="main" class="col-sm-1" style=text-align:left>
          <span style="font-size:30px ; cursor:pointer" onclick="openNav()">&#9776;</span>
        </div>

      <%= link_to root_path, class: "navbar-brand" do %>
          Aaron Eichhorst
          <% end %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-right">

        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact Aaron", contact_us_path %></li>
          <li>
          <%= link_to "https://github.com/piGuy314", target: :_blank  do %>
          <i class="fa fa-github fa-2x"></i>
          <% end %>
        </li>
        <li>
        <%= link_to "https://www.linkedin.com/in/aaron-eichhorst-3a348862/", target: :_blank  do %>
        <i class="fa fa-linkedin-square fa-2x"></i>
        <% end %>
      </li>
      <li>
      <%= link_to "https://www.facebook.com/Examples-in-Programming-202851069731279/", target: :_blank  do %>
      <i class="fa fa-facebook-official fa-2x"></i>
      <% end %>
    </li>
        </ul>

      </div><!-- /.navbar-collapse -->
      </div>
  </nav>


<!--Hamburger Nav data -->
<div id="myRightnav" class="rightnav" >
  <div class="container">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <div class="row">
      <div class="col-md-4">
        <a href="posts">home</a>
        <a href="about">About</a>
        <a href="devmatch">Dev Match</a>
        <a href="site">Free Sites</a>
        <a href="Pong">Pong</a>
        <a href="links">Mock Reddit Site</a>
      </div>

      <div class="col-md-4">
        <a href="devmatch">Ruby</a>
        <a href="javascript">JavaScript</a>
        <a href="java">Java</a>
        <a href="Loaders">Page Loaders</a>
        <a href="SuperMario">Coming Soon</a>
        <a href="SuperMario">Coming Soon</a>
      </div>
      <div class="col-md-4">
        <a href="video">YouTube Videos</a>
        <a href="longform">Forms / Validations</a>
        <a href="Tetris">Tetris</a>
        <a href="SuperMario">Super Mario Brothers</a>
        <a href="More Games">Coming Soon</a>
        <a href="More Games">Coming Soon</a>
      </div>
    </div>
  </div>
</div>



<!-- Success / error message for contact form -->
  <div class = "container">
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
    <% end %>
    <%= yield %>
    </div>
  </div>



<footer class="text-center">
  <nav style="bottom: 0px; width: 100%; height:60px; background-color: lightgray;" class ="navbar navbar-default navbar-fixed-bottom" role="navigation">
      <div class= "container text-center">
        <div class ="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle= "collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class ="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-center">
        </div>
      <ul class="nav navbar-nav navbar text-center">


        <!--
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Aaron", contact_us_path %></li>
        -->

    <li>
        <%= link_to "https://github.com/piGuy314", target: :_blank  do %>
        <i class="fa fa-github fa-2x"></i>
        <% end %>
      </li>
    <li>
      <%= link_to "https://www.linkedin.com/in/aaron-eichhorst-3a348862/", target: :_blank  do %>
      <i class="fa fa-linkedin-square fa-2x"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "https://www.facebook.com/aaron.eichhorst.7?ref=bookmarks", target: :_blank  do %>
      <i class="fa fa-facebook-official fa-2x"></i>
      <% end %>
    </li>
  <!--
      <li><h3>Aaron Eichhorst 2017. All Rights Reserved.</h3></li>
    -->
    </ul>

      </div>
    </div>
  </nav>
</footer>



</html>

app/views/links/_form.html.erb
<%= form_for(link) do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Title </th>
      <th>Url </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.url %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>
<br>
<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/pages/Loaders.html.erb
<head>

<style>

.loader1 {
    border: 16px solid #f3f3f3; /* Light grey */
    border-top: 16px solid #3498db; /* Blue */
    border-radius: 50%;
    width: 120px;
    height: 120px;
    animation: spin 2s linear infinite;
}

.loader2 {
 border-top: 16px solid red;
 border-right: 16px solid green;
 border-bottom: 16px solid red;
 border-left: 16px solid green;
 border-radius: 25%;
 width: 120px;
 height: 120px;
 animation:  2s spin linear infinite;
}


@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}

</style>



</head>
  <body>

  <h1 class="text-center">Different Page Loaders<h1>
    <br>
    <br>
  <div class="loader1"></div>
<br>
<br>
<br>
  <div class="loader2"></div>

  </body>


</head>
<br>
<br>

app/views/pages/PacmanGame.html.erb
<head>
  <h1>PacMan</h1>

  <div class= "dotted">

</head>

<body>
  <div id ='world'>

</div>




</div>
</body>


<script>
  // Pacman game JS

  //Array layout
  // 1 = <div class='wall'></div>
  // 2 = <div class='black'></div>
  // 3 = <div class='dot'></div>
  // 4 = <div class=''></div>
  // 5 = <div class='Pacman'></div>

  var map = [
              [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
              [1,5,3,3,3,3,3,3,3,3,1,3,3,3,3,3,3,3,3,3,1],
              [1,3,1,1,1,3,1,1,1,3,1,3,1,1,1,3,1,1,1,3,1],
              [1,3,1,1,1,3,1,1,1,3,1,3,1,1,1,3,1,1,1,3,1],
              [1,3,1,1,1,3,1,1,1,3,1,3,1,1,1,3,1,1,1,3,1],
              [1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1],
              [1,3,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,3,1],
              [2,3,3,3,3,1,3,3,3,3,3,3,3,3,3,1,3,3,3,3,2],
              [1,3,1,1,3,1,3,1,1,1,1,1,1,1,3,1,3,1,1,3,1],
              [1,3,1,1,3,1,3,1,2,2,2,2,2,1,3,1,3,1,1,3,1],
              [1,3,1,1,3,1,3,1,2,2,2,2,2,1,3,1,3,1,1,3,1],
              [1,3,1,1,3,1,3,1,1,1,1,1,1,1,3,1,3,1,1,3,1],
              [1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1],
              [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
  ]

  var pacman = {
    x: 1,
    y: 1,
  }

var score = 0;

  //algorithm.codingdojo.com

  //console.log(document);


	var el = document.getElementById('world');

	function drawWorld(){
		el.innerHTML = '';
		for(var y = 0; y < map.length ; y = y + 1) {
			for(var x = 0; x < map[y].length ; x = x + 1) {
				if (map[y][x] === 1) {
					el.innerHTML += "<div class='wall'></div>";
				}
				else if (map[y][x] === 2) {
					el.innerHTML += "<div class='black'></div>";
				}
				else if (map[y][x] === 3) {
					el.innerHTML += "<div class='dot'></div>";
				}
				else if (map[y][x] === 4) {
					el.innerHTML += "<div class='ghost'></div>";
				}
				else if (map[y][x] === 5) {
					el.innerHTML += "<div class='Pacman'></div>";
				}
			}
			el.innerHTML += "<br>";
		}
	}


document.onkeydown = function(e){
  console.log(e.keyCode);

  if(e.keyCode === 37){
    // left
    if(map[pacman.y][pacman.x-1] !==1){
      map[pacman.y][pacman.x] =2;
      pacman.x = pacman.x - 1;
      map[pacman.y][pacman.x] =5;
      drawWorld();
    }
  }
  else if(e.keyCode === 38){
    // up
    if(map[pacman.y-1][pacman.x] !== 1){
      map[pacman.y][pacman.x] =2
      pacman.y = pacman.y -1;
      map[pacman.y][pacman.x] =5;
      drawWorld();
    }
  }
  else if(e.keyCode === 39){
    // right
    if(map[pacman.y][pacman.x+1] !==1){
      map[pacman.y][pacman.x] =2;
      pacman.x = pacman.x + 1;
      map[pacman.y][pacman.x] =5;
      drawWorld();
      }
    }
  else if(e.keyCode === 40){
    // down
    if(map[pacman.y+1][pacman.x] !==1){
      map[pacman.y][pacman.x] =2;
      pacman.y = pacman.y + 1;
      map[pacman.y][pacman.x] =5;
      drawWorld();
      }
    }
}
drawWorld();

function score(){

}




</script>

app/views/pages/Pong.html.erb
<html>
<head>
  <h1>Dev Pong</h1>
</head>
<body>




<img src = "https://www-assets0.herokucdn.com/assets/products/platform-86ed035335ac2a59e85e00773b18ec6baa851f2e37fd98f1c0237f609423eca9.png"></img>

<%= audio_tag "Pong_Beat.m4a", class: "audio-play" %>
<p class="btn btn-primary audioButton">Play</p>

  <canvas id="pong" width="600" height="400"/>

  <script>

  $(".audioButton").on("click", function() {
  $(".audio-play")[0].currentTime = 0;
  return $(".audio-play")[0].play();
});
</script>
  </body>

</html>

app/views/pages/Reddit.erb
<html>

<head>
  <h1>Reddit</h1>



  </head>
  <body>


  </body>



</html>

app/views/pages/SuperMario.erb
<html>

<head>
  <h1>Super Mario</h1>



  </head>
  <body>
    <canvas id="screen" width="640" height="640"></canvas>
  </body>

<script type="module" >

function loadImage(url) {
  return new Promise(resolve => {
    const image = new Image();
    image.addEventListener('load', () => {
      resolve (image);
    });
    image.src = url;
  });
}

const canvas = document.getElementById('screen');
const context = canvas.getContext('2d');

context.fillRect(0,0,50,50);

loadImage('/images/tiles.png')
.then(image => {
  context.drawImage(image, 0, 0);

});
function hello() {
  alert("Still not working yet :(");
}
hello();

</script>



</html>

<!-- src="/app/assets/javascripts/main.js" -->

app/views/pages/devmatch.html.erb
<div class="home-callout text-center ">
    <h1>Welcome to DevMatch!</h1>
    <h3>A mock membership site for entrepeures to meet developers. </h3>
  </div>
<div class="container home-signup-links">
  <div class="row">
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">Basic Membership</h2>
          <h4>Sign up for free and get basic access to the community.</h4>
          <br/>
          <br/>
        </div>
        <a href="/users/sign_up" class="btn btn-primary btn-lg btn-block btn-success">Sign up with Basic</a>
      </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Pro Membership</h2>
          <h4>Sign up for Pro account for $10/month. You'll get all the basic membership features plus so much more!</h4>
          <br/>
      </div>
      <a href="/users/sign_up" class="btn btn-primary btn-lg btn-block btn-success">Sign up with Pro</a>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div id="main ">
    <div class="col-md-10 col-md-offset-2">
      <h1 class="text-center">Welcome to my site!</h1>
      <h3 class="text-center">I've created this site as a portfolio page to display my accomplishemnets in front and back end web design.</h3>
  
      <!-- Need to work on image position with browser resizing
        <img class= me  src="https://scontent-ord1-1.xx.fbcdn.net/v/t1.0-9/15319097_10211166392421461_2269551270510495837_n.jpg?oh=a4f28fa48a8581d11800470e75233bb2&oe=597F4FD2" >
      -->
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body,  size: "30x10" %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/home.html.erb
<!-- Duplicate to posts/index.html.erb - waiting to delete
<div class="container">
  <div id="main ">
    <div class="col-md-10 col-md-offset-2">
      <h1 class="text-center">Welcome to my site!</h1>
      <h3 class="text-center">I've created this site as a portfolio page to display my accomplishemnets in front and back end web design.</h3>

       Need to work on image position with browser resizing
        <img class= me  src="https://scontent-ord1-1.xx.fbcdn.net/v/t1.0-9/15319097_10211166392421461_2269551270510495837_n.jpg?oh=a4f28fa48a8581d11800470e75233bb2&oe=597F4FD2" >
    </div>
  </div>
</div>
-->

app/views/posts/index.html.erb
<!--Need to work on positioning of self image
  <img class= me  src="https://scontent-ord1-1.xx.fbcdn.net/v/t1.0-9/15319097_10211166392421461_2269551270510495837_n.jpg?oh=a4f28fa48a8581d11800470e75233bb2&oe=597F4FD2" >
-->


<body class="body">
<div class="row">
<div class="col-md-3">
  <h1 class="text-center"></h1>
  <%= image_tag"Me.png", :height => '290px', :width => '270px' %>

    <h5>I'm Aaron Eichhorst, a software developer in the Chicago land area. <a href="about" style=color:skyblue>More about me.</a></h5>

</header>
</div>
<p id="notice"><%= notice %></p>

<div class= "col-md-8">
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path, class: 'newPost btn btn-success' %>
<% end %>
<br>
<br>
<!-- commenting out for now
<h1 class="text-center">Posts</h1>
-->
<div class="">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <div class="post_wrapper">
          <h1 class="title"><%= link_to post.title, post %></h1>
          <h3 class="body"><%= link_to post.body, post %></h3>
          <h3 class="date"><%= post.created_at.strftime("%B, %d, %Y") %></h3>
          <h3 class="comments">Comments: <%= link_to post.comments.count, post %></h3>
        <!-- removed: used titel, body and date with different HTML / Ruby above
        <td><%= post.title %></td><br><br>
        <td><%= post.body %></td><br><br><br>
        -->

        <td><%= link_to 'View', post, class: 'btn ' %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: 'btn ' %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn ' %></td>
      </tr>
    <% end %>





  </tbody>
</div>
</div>
</div>
</body>



</header>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong class="title">Title:</strong>
  <%= @post.title %>
</p>

<p class="date">
  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
</p>

<p>
  <strong class="body">Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>